### ISSUE TITLE
Develope should be Develop

### ISSUE THREAD

**Issue by nmschorr** [nuls-io/devsite#16]
In the vue.js script:
 https://github.com/nuls-io/devsite/blob/master/docs/.vuepress/config.js
   line 37:
                {text:"Develope",link:"/Docs/"}
The spelling should be 'Develop'.

Since this is just the text label on a link, changing it won't matter.  Develope is the obsolete spelling.  

![image](https://user-images.githubusercontent.com/12592910/64746172-692e6100-d4bf-11e9-9f62-e1112fcbb54c.png)

**Comment by CQBeer** [comment]
fixed

**Comment by nmschorr** [comment]
Thank you Pen!
